version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs",
    "angular",
    "vue"
  ]
  environment = [
    "nodejs",
    "mongo",
    "vitest"
  ]